### ISSUE TITLE
按照博主的配置好后，事件没有反应SDK版本有没有限制

### ISSUE THREAD

**Issue by coolJason** [ttpai/Tracker#5]
事件触发时有报一些错误

**Comment by coolJason** [comment]
W/System.err: java.lang.NoSuchFieldException: No field mScroller in class Lcom/google/android/material/appbar/AppBarLayout$BaseBehavior

**Comment by coolJason** [comment]
at java.lang.Class.getDeclaredField(Native Method)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at com.bintiger.mall.behavior.AppBarLayoutBehavior.getScrollerField(AppBarLayoutBehavior.java:93)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at com.bintiger.mall.behavior.AppBarLayoutBehavior.stopAppbarLayoutFling(AppBarLayoutBehavior.java:117)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at com.bintiger.mall.behavior.AppBarLayoutBehavior.onStartNestedScroll(AppBarLayoutBehavior.java:149)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at com.bintiger.mall.behavior.AppBarLayoutBehavior.onStartNestedScroll(AppBarLayoutBehavior.java:23)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at androidx.coordinatorlayout.widget.CoordinatorLayout.onStartNestedScroll(CoordinatorLayout.java:1783)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at androidx.core.view.ViewParentCompat.onStartNestedScroll(ViewParentCompat.java:209)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at androidx.core.view.NestedScrollingChildHelper.startNestedScroll(NestedScrollingChildHelper.java:153)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at androidx.recyclerview.widget.RecyclerView.startNestedScroll(RecyclerView.java:11908)
2021-12-14 17:02:28.123 14039-14039/com.bintiger.mall.android W/System.err:     at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:3350)

**Comment by coolJason** [comment]
继承这个BaseActivity就不行了public abstract class BaseActivity<VM extends BaseViewModel> extends AppCompatActivity，如果只是简单的继承AppCompatActivity就可以，请教下博主

**Comment by Zihao-Wu** [comment]
1、与sdk无关，android系统无关。
2、这个报错应该和这个框架毫无关系。明显是androidx。。。
3：你监控的是什么事件，麻烦贴下代码。那个没有生效？

**Comment by coolJason** [comment]
Application配置
        Track.initTrack(this);
        Pointer.getInstance().registerEvent();                                                                                                                                  
Pointer 代码
public void registerEvent() {
        Track.from(AActivity.class).to(BActivity.class).subscribe(new OnEvent() {
            @Override
            public void onEvent() {
                Log.d(TAG, "A->B");

            }
        });
    }
项目 build配置classpath 
 classpath 'com.hujiang.aspectjx:gradle-android-plugin-aspectjx:2.0.10'
app build配置
apply plugin: 'com.hujiang.android-aspectjx'
implementation 'com.github.ttpai:Tracker:1.0.4'

**Comment by coolJason** [comment]
aspectjx{
        exclude 'androidx','com.google','com.squareup','leakcanary','com.taobao','com.ut','android.support','versions.9'
    }

**Comment by coolJason** [comment]
aspectjx{
        exclude 'androidx','com.google','com.squareup','leakcanary','com.taobao','com.ut','android.support','versions.9'
    }
appbuild配置了这个，不然一直报zip file is empty

**Comment by Zihao-Wu** [comment]
> 

把 ‘ androidx’ 这个去掉，贴一个我项目中用的配置：
aspectjx {
    exclude '.jar'
    exclude 'com.umeng.message'
    exclude 'com.taobao'
    exclude 'anet.channel.util'
    exclude 'com.alipay'
    exclude 'com.squareup.leakcanary'
    exclude 'versions.9'
}

**Comment by Zihao-Wu** [comment]
我在demo工程中改为baseActivity ，试了是没问题的。

**Comment by coolJason** [comment]
可以了，就是把androidx去掉就行了，谢谢~
